x-veld:
  code:
    description: "A demo code veld, integrating the tag_ud script. For more documentation, 
      see: https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#tag_ud"
    topic:
      - NLP
      - ETL

    input:
      - volume: /veld/input/
        environment_var: in_txt_file
        file_type: txt

    output:
      - volume: /veld/output/
        environment_var: out_conllu_file
        file_type:
          - tsv
          - conllu

    config:
      - environment_var: model
        var_type: str
      - environment_var: batch
        var_type: int
        default: 1000
        optional: true
      - environment_var: verbose
        var_type: bool
        default: false
        optional: true

services:
  veld_tag_ud:
    build: .
    volumes:
      - ./:/veld/code/
      - ./data/tag_ud/in/:/veld/input/
      - ./data/tag_ud/out/:/veld/output/
    command: ./veld_tag_ud.sh
    environment:
      in_txt_file: null
      out_conllu_file: null
      model: null
      batch: 1000
      verbose: false

