x-veld:
  code:
    description: "A demo code veld, integrating the standoff2xml script. For more documentation, 
      see: https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#standoff2xml"
    topic:
      - NLP
      - ETL

    input:
      - volume: /veld/input/
        environment_var: in_txt_file
        file_type: txt
      - volume: /veld/input/
        environment_var: in_json_file
        file_type: json
      - volume: /veld/input/
        environment_var: in_ann_json_file
        file_type: json

    output:
      - volume: /veld/output/
        environment_var: out_ann_xml_file
        file_type: xml

    config:
      - environment_var: token_annotation
        var_type: bool
        default: false
        optional: true
      - environment_var: warn_breaking
        var_type: str
        optional: true
      - environment_var: keep_between_sentences
        var_type: bool
        default: false
        optional: true

services:
  veld_standoff2xml:
    build: .
    volumes:
      - ./:/veld/code/
      - ./data/standoff2xml/in/:/veld/input/
      - ./data/standoff2xml/out/:/veld/output/
    command: bash /veld/code/veld_standoff2xml.sh
    environment:
      in_txt_file: null
      in_json_file: null
      in_ann_json_file: null
      out_ann_xml_file: null
      token_annotation: false
      warn_breaking: null
      keep_between_sentences: false

