x-veld:
  code:
    description: "A demo code veld, integrating the xml2standoff script. For more documentation, 
      see: https://github.com/czcorpus/xmlanntools?tab=readme-ov-file#xml2standoff"
    topic:
      - NLP
      - ETL

    input:
      - volume: /veld/input/
        environment_var: in_xml_file
        file_type: xml

    output:
      - volume: /veld/output/
        environment_var: out_txt_file
        file_type: txt
      - volume: /veld/output/
        environment_var: out_json_file
        file_type: json

    config:
      - environment_var: text_elements
        var_type: str
        optional: true
      - environment_var: exclude_elements
        var_type: str
        optional: true
      - environment_var: keep_linebreaks
        var_type: bool
        default: false
        optional: true

services:
  veld_xml2standoff:
    build: .
    volumes:
      - ./:/veld/code/
      - ./data/xml2standoff/in/:/veld/input/
      - ./data/xml2standoff/out/:/veld/output/
    command: bash /veld/code/./veld_xml2standoff.sh
    environment:
      in_xml_file: null
      out_txt_file: null
      out_json_file: null
      text_elements: null
      exclude_elements: null
      keep_linebreaks: false

